### PR TITLE
For #29105 - Logging to the script editor is now always done on the main thread

### PR DESCRIPTION
**Pull request by alandann**

### CODE REVIEW

**Comment by jfboismenu-adsk** [comment]
Looks great, but shouldn't we introduce a ```fire_and_forget``` argument on ```execute_in_main_thread``` at the same time so that logging doesn't slow down the execution since it is a blocking call?

I believe using ```QtCore.Qt.QueuedConnection``` when calling ```QObject.invokeMethod``` would allow us to fire and forget, am I right?

**Comment by alandann** [comment]
That's a good idea - it will need a new argument though and a change to the engine code...

**Comment by alandann** [comment]
actually, because of the way it's written it may need a new method on the engine, something like `execute_in_main_thread_async()`...

**Comment by alandann** [comment]
or even `execute_in_main_thread_non_blocking()` which is less contradictory but a bit of a mouthful :(

**Pull request closed without merging**
